schema: "classroom50/repo-config/v1"
classroom: "agi"
assignment: "github-pages"
owner:
  username: "ebinmv"
  id: 204208148
  accepted_at: "2026-09-02T00:13:32Z"
source:
  owner: "gsm-class"
  owner_id: 318515310
  repo: "github-pages"
  branch: "main"
